window.EMX_PRODUCTS = [
  {
    id: "custom_os",
    key: "Isg28",
    productUrl: "https://payhip.com/b/Isg28",
    title: "EMX Custom OS",
    eyebrow: "Windows 10 + 11 Custom OS",
    price: 20.99,
    oldPrice: 49.99,
    image: "./assets/emx-os/emx-payhip-overview.png",
    gallery: [
      "./assets/emx-os/emx-payhip-overview.png",
      "./assets/emx-os/emx-payhip-smart-tune.png",
      "./assets/emx-os/emx-payhip-personalize.png",
      "./assets/emx-os/emx-payhip-support.png",
      "./assets/emx-os/emx-os-v1320-security.png"
    ],
    previewType: "image",
    previewSrc: "./assets/emx-os/emx-payhip-overview.png",
    fallbackPreview: "./assets/emx-os/emx-payhip-overview.png",
    description: "EMX Custom OS v1.3.20 is a Windows 10 and 11 gaming optimization and visual identity package with hardware-aware Smart tuning, five animated EMX scenes, one-key Gaming Mode, change evidence, recovery tools, and seamless updates.",
    features: [
      "Smart profile scans hardware and chooses Safe or Balanced automatically",
      "Compatibility-safe Windows 10 and 11 tuning for gaming, streaming, Discord, OBS, controllers, audio, networking, and updates",
      "Five original animated EMX scenes with a rebindable static Gaming Mode toggle",
      "Before-and-after change evidence, support bundles, restore tools, and rollback controls",
      "Seamless in-app updates connected to official GitHub releases",
      "EMX license claim flow using Payhip email and receipt transaction ID"
    ],
    featured: true,
    bestSeller: true,
    saleBadge: "v1.3.20",
    tags: ["Windows 10 + 11", "Live wallpapers", "Smart profiles", "Restore-first"],
    visible: true
  },
  {
    id: "windows_tweak_dashboard",
    key: "TJFav",
    productUrl: "https://payhip.com/b/TJFav",
    title: "EMX Windows Tweak Dashboard",
    eyebrow: "Safe Reversible Windows Tweaks",
    price: 20.99,
    oldPrice: 0,
    image: "./app-screenshots/emx-windows-tweak-dashboard-01-overview.png",
    gallery: [
      "./app-screenshots/emx-windows-tweak-dashboard-01-overview.png",
      "./app-screenshots/emx-windows-tweak-dashboard-02-low-latency.png",
      "./app-screenshots/emx-windows-tweak-dashboard-03-performance-tools.png",
      "./app-screenshots/emx-windows-tweak-dashboard-04-game-session.png",
      "./app-screenshots/emx-windows-tweak-dashboard-05-qol.png",
      "./app-screenshots/emx-windows-tweak-dashboard-06-startup.png",
      "./app-screenshots/emx-windows-tweak-dashboard-07-profiles.png",
      "./app-screenshots/emx-windows-tweak-dashboard-08-backups.png",
      "./app-screenshots/emx-windows-tweak-dashboard-09-logs.png"
    ],
    previewType: "image",
    previewSrc: "./app-screenshots/emx-windows-tweak-dashboard-01-overview.png",
    fallbackPreview: "./app-screenshots/emx-windows-tweak-dashboard-01-overview.png",
    description: "EMX Windows Tweak Dashboard is a safe, reversible Windows optimization toolkit for smoother gaming, cleaner startup, low-latency tuning, Game Session Mode, before/after FPS reports, network checks, guided profiles, backups, and restore tools.",
    features: [
      "Safe reversible tweak dashboard with backups before changes",
      "Low-latency, power plan, timer, startup, and network tuning tools",
      "Game Session Mode plus before/after FPS benchmark reporting",
      "Guided profiles, Undo Center, action logs, and one-PC license activation"
    ],
    featured: true,
    saleBadge: "NEW TWEAKS",
    tags: ["Reversible", "Low latency", "Backups"],
    visible: true
  },
  {
    id: "clips",
    key: "8vBPZ",
    productUrl: "https://payhip.com/b/8vBPZ",
    title: "EMX Clips",
    eyebrow: "Instant Replay for Windows",
    price: 1.00,
    oldPrice: 0,
    image: "./assets/emx-clips/emx-clips-cover.png",
    gallery: [
      "./assets/emx-clips/emx-clips-cover.png",
      "./assets/emx-clips/emx-clips-ready.png",
      "./assets/emx-clips/emx-clips-library.png",
      "./assets/emx-clips/emx-clips-settings.png"
    ],
    previewType: "image",
    previewSrc: "./assets/emx-clips/emx-clips-cover.png",
    fallbackPreview: "./assets/emx-clips/emx-clips-cover.png",
    description: "EMX Clips is a local-first Windows instant replay app for Fortnite and competitive PC gameplay. Keep replay armed, press your own global hotkey after a moment worth saving, and manage the finished clip from a clean EMX library.",
    features: [
      "Replay can arm automatically on launch and stays ready after every saved clip",
      "Press-to-bind global hotkeys for saving clips and showing or hiding the app",
      "In-game notifications confirm when replay is ready and when a clip is saved",
      "NVIDIA NVENC capture with system audio and optional microphone recording",
      "Local clip library with previews, favorites, storage controls, and share-ready file copying",
      "No account, telemetry, or automatic cloud uploads"
    ],
    featured: true,
    saleBadge: "NEW RELEASE",
    tags: ["Instant replay", "NVENC", "Local-first", "Windows"],
    homepage: false,
    licenseClaim: false,
    visible: true
  },
  {
    id: "macro",
    key: "0TOjr",
    productUrl: "https://payhip.com/b/0TOjr",
    title: "EMX Premium KBM Macro (Retired)",
    eyebrow: "Retired Product",
    price: 15.00,
    oldPrice: 35.00,
    image: "./macro.png",
    gallery: ["./macro.png", "./macro2.png", "./macro3.png"],
    previewType: "image",
    previewSrc: "./macro.png",
    fallbackPreview: "./macro.png",
    description: "EFECT keyboard profile interface built for saved binds, clean toggle controls, delay adjustment, and fast profile switching. Designed for simple setup, organized controls, and a polished EMX dashboard feel with Payhip receipt-based EMX license claiming.",
    features: [
      "Saved keybind profile system",
      "Toggle-based macro controls",
      "Adjustable delay settings",
      "Low-latency timing controls"
    ],
    homepage: false,
    visible: false,
    retired: true
  },
  {
    id: "controller_macro",
    key: "ArZlF",
    productUrl: "https://payhip.com/b/ArZlF",
    title: "EMX Elite Controller Macro (Retired)",
    eyebrow: "Retired Product",
    price: 29.99,
    oldPrice: 49.99,
    image: "./controller-macro.png",
    gallery: [
      "./controller-macro.png",
      "./controller-macro-dashboard.png",
      "./controller-macro-gallery.png",
      "./controller-macro-logo-card.png",
      "./controller-macro-hero.png"
    ],
    previewType: "image",
    previewSrc: "./controller-macro.png",
    fallbackPreview: "./controller-macro.png",
    description: "Fast native controller macro utility built around a clean Double Edit workflow, controller-ready diagnostics, protected presets, speed/catch control, and native PC controller input paths. Includes portable EXE plus customer README.",
    features: [
      "Native controller input engine with controller-ready status",
      "Double Edit preset with speed/catch control",
      "Hex-style Sony HID and SCUF-style controller support path",
      "Touchpad, paddle, face button, trigger, and stick button binding options",
      "No DS4Windows requirement"
    ],
    saleBadge: "New Controller Drop",
    homepage: false,
    visible: false,
    retired: true
  },
  {
    id: "volt",
    key: "Oqz73",
    productUrl: "https://payhip.com/b/Oqz73",
    title: "EMX VOLT MACRO",
    eyebrow: "NEW Rust Engine Drop",
    price: 25.00,
    oldPrice: 50.00,
    image: "./app-screenshots/emx-volt-dashboard-real.png",
    gallery: [
      "./app-screenshots/emx-volt-dashboard-real.png",
      "./app-screenshots/emx-volt-macros-real.png",
      "./app-screenshots/emx-volt-binds-real.png",
      "./app-screenshots/emx-volt-support-real.png"
    ],
    previewType: "image",
    previewSrc: "./app-screenshots/emx-volt-dashboard-real.png",
    fallbackPreview: "./app-screenshots/emx-volt-dashboard-real.png",
    description: "EMX VOLT MACRO is the newest EMX Windows desktop macro app with a Rust-powered runtime, premium glass UI, saved binds, timing controls, tray support, emergency stop, Payhip license keys, and built-in update checking.",
    features: [
      "Tauri + Rust Windows desktop engine",
      "Lifetime single-PC Payhip license access",
      "Saved keybinds, mouse buttons, and timing controls",
      "Built-in updater, tray controls, and emergency stop"
    ],
    featured: true,
    saleBadge: "NEW",
    tags: ["Macro", "Rust runtime", "Saved binds"],
    homepage: false,
    visible: true
  },
  {
    id: "fps",
    key: "EQIrd",
    productUrl: "https://payhip.com/b/EQIrd",
    title: "EMX FPS Booster",
    eyebrow: "Performance Pack",
    price: 10.99,
    oldPrice: 21.98,
    image: "./fps.png",
    gallery: ["./fps.png", "./fps2.png", "./fps3.png", "./fps4.png"],
    previewType: "image",
    previewSrc: "./fps.png",
    fallbackPreview: "./fps.png",
    description: "A lightweight performance tuning pack built to help your PC feel cleaner, faster, and smoother during gameplay, with EMX license claiming tied to the Payhip receipt after checkout.",
    features: [
      "Game-priority tuning for smoother gameplay feel",
      "Background app reduction and cleanup workflow",
      "Display responsiveness and smoothness optimization presets",
      "Simple performance setup flow"
    ],
    tags: ["Gaming", "Cleanup", "Smoothness"],
    visible: true
  },
  {
    id: "os_macro_bundle",
    key: "By7FV",
    productUrl: "https://payhip.com/b/By7FV",
    title: "EMX Windows Tweaks + VOLT Bundle",
    eyebrow: "Current Bundle Deal",
    price: 39.99,
    oldPrice: 84.99,
    image: "./app-screenshots/emx-windows-tweak-dashboard-01-overview.png",
    gallery: [
      "./app-screenshots/emx-windows-tweak-dashboard-01-overview.png",
      "./app-screenshots/emx-windows-tweak-dashboard-02-low-latency.png",
      "./app-screenshots/emx-volt-dashboard-real.png",
      "./app-screenshots/emx-volt-macros-real.png",
      "./app-screenshots/emx-volt-binds-real.png"
    ],
    previewType: "image",
    previewSrc: "./app-screenshots/emx-windows-tweak-dashboard-01-overview.png",
    fallbackPreview: "./app-screenshots/emx-windows-tweak-dashboard-01-overview.png",
    description: "A current two-product EMX bundle for the Windows Tweak Dashboard and EMX VOLT MACRO. One Payhip checkout keeps the performance tools and macro setup together with a shared EMX license claim path.",
    features: [
      "EMX Windows Tweak Dashboard with reversible tuning, profiles, backups, and restore tools",
      "EMX VOLT MACRO with saved bind profiles, timing controls, and updater support",
      "One shared EMX license claim flow for both products",
      "Discord setup support for OS install and macro access"
    ],
    tags: ["Bundle", "Windows tweaks", "VOLT macro"],
    type: "bundle",
    page: "bundle",
    homepage: false,
    visible: true
  },
  {
    id: "bundle",
    key: "Bundle",
    productUrl: "https://payhip.com/buy?link=Bundle",
    title: "EMX Ultimate Tweak Pack",
    eyebrow: "Best Value Bundle",
    price: 59.99,
    oldPrice: 109.99,
    image: "./emx-logo.png",
    gallery: [
      "./app-screenshots/emx-windows-tweak-dashboard-01-overview.png",
      "./macro.png",
      "./fps.png"
    ],
    previewType: "image",
    previewSrc: "./emx-logo.png",
    fallbackPreview: "./emx-logo.png",
    description: "Built for buyers who want the full EMX setup in one pack with the Windows Tweak Dashboard, FPS booster, and EFECT Pro Keyboard Macro dashboard. Buyers claim or recover their EMX license from the Payhip receipt after checkout.",
    features: [
      "EMX Windows Tweak Dashboard for safe reversible tuning, profiles, backups, and restore tools",
      "FPS Booster for smoother gameplay profile setup and background reduction",
      "EFECT Pro Keyboard Macro dashboard with saved bind controls",
      "Priority support guidance"
    ],
    homepage: false,
    visible: false,
    retired: true
  }
];
